### PR TITLE
README edits

### PR DESCRIPTION
**Pull request by shayneofficer**
## Pull request content
- [ ] ENHANCEMENT
- [ ] BUGFIX

**Related task:** <put link here>

Describe here technical detail omitted on task

## Notes for admin
What the pull request admin must know before review it

### CODE REVIEW

**Comment by shayneofficer** [comment]
@zeppaman no problem! I actually think I would like to join, I'm trying to learn more about .NET Core / Docker / Kubernetes. I'll fill out the form linked in the README 👍

**Comment by zeppaman** [comment]
@shayneofficer  great! In this project, there is some very interesting  asp.net core stuff. I think it may be a good place where to expand your .net knowledge. if you prefer we can have a quick chat on Gitter instead of filling the survey. The role of the survey is just to understand how you want to contribute and sare direct contact.

**Comment by zeppaman** [comment]
@shayneofficer I received a survey, but without any contact. Sorry for asking but, it was you? In case please let me know how to add you to Slack or Gitter channels.

**Comment by shayneofficer** [comment]
@zeppaman Hey, sorry for the delayed response! Nope, that wasn't me - I haven't filled out the survey. I'd be happy to chat on Gitter as you suggested though!

**Comment by zeppaman** [comment]
@shayneofficer great! Just drop me a message to start the chat.

**Pull request merged**
