### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by chriswmercer**
I hope its ok, I've made some minor amendments to the readme to help it read smoother

## Pull request content
- [*] ENANCHEMENT
- [ ] BUGFIX

**Related task:** <put link here>

Just some readme improvments

## Notes for admin
What the pull request admin must know before review it

### CODE REVIEW

**Comment by th0mk** [comment]
Spam hacktoberfest request, don't bother.

**Comment by chriswmercer** [comment]
@th0mk it isn't spam, I saw some issues with the text and correct it. I'm new to helping with public repos (despite having been a dev for a long time) and wanted to see how it all worked.

**Review by zeppaman — APPROVED** [review]

**Comment by chriswmercer** [comment]
@zeppaman thank you sir

**Comment by chriswmercer** [comment]
Hold up - if it has an invalid tag, how can it be merged?

**Pull request merged**
