### PR TITLE
 Update C# Language Version in all RawCMS Projects

### PR DESCRIPTION
**Pull request by AaqibAhamed**
## Pull request content
- [x] ENANCHEMENT
- [ ] BUGFIX

**Related task:** <https://github.com/arduosoft/RawCMS/issues/270>

No thechnical detail omitted on task

## Notes for admin
After this fix C# compiler automatically determine latest language version based on project's target framework or frameworks.This **ensures that for whatever target our project is built against, get the highest compatible language version by default.**

The latest C# compiler determines a default language version based on your project's target framework or frameworks. This is because the C# language may have features that rely on types or runtime components that are not available in every .NET implementation.

### CODE REVIEW

**Comment by AaqibAhamed** [comment]
Can anyone please review it

**Review by zeppaman — APPROVED** [review]

**Comment by zeppaman** [comment]
@AaqibAhamed thank you for the contribution. PR is accepted. You missed accepting the CLA agreement, then we can merge to the master branch.

**Comment by AaqibAhamed** [comment]
> @AaqibAhamed thank you for the contribution. PR is accepted. You missed accepting the CLA agreement, then we can merge to the master branch.

I have signed to  CLA agreement

**Comment by AaqibAhamed** [comment]
@zeppaman  can you check what is the issue.?.I have signed CLA with my GitHub Account.But it's not showing here

**Comment by AaqibAhamed** [comment]
Can anyone find what's the issue with CLA ?

**Comment by zeppaman** [comment]
@AaqibAhamed the changes are committed by @Aaqibwiki, wich user did you use for signing? the bot checks in the committers list. Anyway, I can marge it manually as the changes are small and you already told you have signed it.

**Comment by AaqibAhamed** [comment]
> @AaqibAhamed the changes are committed by @Aaqibwiki, wich user did you use for signing? the bot checks in the committers list. Anyway, I can marge it manually as the changes are small and you already told you have signed it.

Both @AaqibAhamed and @Aaqibwiki  are my accounts.I have used @AaqibAhamed  for sign.Do I need to sign  into CLA by using @Aaqibwiki  ? .But repo forked into @AaqibAhamed account..Thank you

**Pull request merged**
